/* UI dictionary. Keep customer-entered names, identifiers, documents and business records unchanged. */
const AZURE_EN={
 '主選單':'Main menu','儀表板':'Dashboard','商戶入網':'Merchant onboarding','新增商戶':'New merchant','新增客戶':'New customer','批量導入':'Bulk import','商戶管理':'Merchants','內審控制台':'Internal review','查閱更新記錄':'Activity log','帳號管理':'Accounts','已儲存的草稿':'Saved drafts','設定':'Settings','登出':'Sign out',
 '登入':'Sign in','登 入':'Sign in','商戶登入':'Merchant sign-in','電郵地址':'Email address','密碼':'Password','請輸入':'Enter a value','請輸入 Demo 密碼':'Enter Demo password','忘記密碼？':'Forgot password?','或':'or','使用 Google 登入':'Continue with Google','使用電郵驗證碼登入':'Sign in with email code','未有帳戶？ 建立帳戶':'No account? Register','返回登入':'Back to sign in','開啟外部商戶申請':'Open external application','建立帳戶':'Create account','姓名':'Name','設定密碼':'Create password','確認密碼':'Confirm password','立即申請':'Apply now','商戶註冊':'Merchant registration','提取已儲存草稿':'Retrieve a saved draft','我的申請':'My applications',
 '文件材料':'Documents','主體資料':'Entity information','經營與聯繫':'Business & contacts','結算帳戶':'Settlement account','產品與費率':'Products & fees','確認提交':'Review & submit','KTC 認證':'KTC verification','上一步':'Back','下一步':'Next','儲存草稿':'Save draft','提交申請':'Submit application','完成':'Done','關閉':'Close','取消':'Cancel','確認':'Confirm','清除':'Clear','重設':'Reset','搜尋':'Search','上一頁':'Previous','下一頁':'Next','填入完整示例':'Fill demo data','清空表單':'Clear form','全部欄位':'All fields','全部狀態':'All statuses','搜尋範圍':'Search scope','商戶狀態':'Merchant status','跨欄位搜尋':'Search all fields','欄位設定':'Columns','匯出 CSV':'Export CSV',
 '兩步驟驗證':'Two-step verification','驗證器驗證碼':'Authenticator code','請輸入 6 位數驗證碼':'Enter the 6-digit code','驗證並登入':'Verify and sign in','改用備用碼':'Use a backup code','綁定驗證器':'Set up authenticator','驗證並啟用':'Verify and enable','保存備用碼':'Save backup codes','下載備用碼（Demo）':'Download backup codes (Demo)','我已保存備用碼':'I have saved the backup codes','完成註冊':'Complete registration','使用備用碼':'Use a backup code','備用碼':'Backup code','驗證備用碼':'Verify backup code','返回驗證器':'Back to authenticator','驗證電郵地址':'Verify email address','電郵驗證碼':'Email verification code','驗證電郵':'Verify email',
 '開啟驗證器，輸入此帳戶的 6 位數驗證碼。':'Open your authenticator and enter the 6-digit code.','Demo 請輸入 123456；此處不驗證真實 TOTP。':'Enter 123456 for this demo. No real TOTP is verified.','Demo 請輸入 123456，不使用真實驗證器。':'Use 123456 in this demo, not a real authenticator.','前端 Demo · 電郵、OTP 與帳戶保護皆為模擬。請勿輸入真實密碼。':'Frontend demo: email, OTP and account protection are simulated. Do not enter real credentials.','驗證碼不正確，Demo 請輸入 123456。':'Incorrect code. Use 123456 for this demo.','驗證工作階段已過期，請返回登入後重試。':'Verification session expired. Return to sign in and try again.','備用碼不正確或已使用，請換一組。':'Invalid or already-used backup code. Try another code.','每組示例備用碼僅能在本瀏覽器使用一次。':'Each demo backup code can be used once in this browser.','請先保存備用碼並勾選確認。':'Save your backup codes and tick the confirmation.','請妥善保存備用碼。每組只能使用一次。':'Keep your backup codes safe. Each can be used only once.','兩步驟驗證已啟用（Demo）。以下不是正式帳戶憑證。':'Two-step verification enabled (Demo). These are not production credentials.',
 '邀請客戶填寫':'Invite a customer','分享我的申請連結':'Share my application link','風控評分（系統參考）':'Risk score (reference)','系統建議':'System recommendation','資料核對與缺件':'Data checks & missing documents','提交完整度':'Application completeness','評分明細與處置':'Score details & handling','資料不一致':'Data mismatches','差異待人工確認':'Differences awaiting review','缺件／需重新提供':'Missing / replacement required','補件通知':'Supplement request','未發送':'Not sent','查看核對明細 →':'View checks →','查看缺件 →':'View missing documents →','目前無阻擋項':'No blocking issues','處理':'Process','查看商戶':'View merchant',
 '核對身分證資訊':'Review ID information','開始 KTC 認證':'Start KTC verification','重新進行 KTC 認證':'Restart KTC verification','查看／核對已導入身分證資訊':'Review imported ID information','確認資料正確':'Confirm information','返回 KTC':'Back to KTC','返回文件材料':'Back to documents','下一步：主體資料':'Next: entity information','手機拍照 — 身分證':'Take an ID photo','人像識別':'Face verification','識別成功（Demo）':'Verification successful (Demo)','識別成功':'Verification successful','需要手機拍照及人像識別':'ID photo and face verification required','使用手機完成 KTC 認證':'Complete KTC on your phone','識別連結已過期':'Verification link expired','重新產生 QR Code':'Generate a new QR code','取消識別':'Cancel verification','模擬識別成功回傳':'Simulate successful callback','模擬連結過期':'Simulate expired link','手機 Demo 回傳碼':'Mobile demo return code','確認手機回傳碼':'Confirm mobile return code','開啟手機識別 Demo ↗':'Open mobile verification demo ↗','繼續下一步':'Continue','查看 KTC':'View KTC','請先完成 KTC 認證':'Complete KTC verification first','回傳碼不正確':'Incorrect return code','安全身分認證 · KTC · Demo':'Identity verification · KTC · Demo','開始認證':'Start verification','使用示例照片':'Use demo photo','確認並繼續':'Confirm and continue','重新拍照':'Retake photo','完成人像識別（Demo）':'Complete face verification (Demo)','預覽無法識別':'Preview failed verification','暫時無法識別':'Unable to verify','重新進行人像識別':'Retry face verification','我了解並同意進行 Demo 演示':'I understand and agree to run this demo','已核對示例辨識資料':'I have reviewed the demo ID information','身分證相機預覽（示意）':'ID camera preview (illustration)',
 '選擇文件':'Choose file','重新選擇':'Choose again','移除':'Remove','預覽':'Preview','匯入 BR':'Import BR','多文件辨識':'Multi-document recognition','開始辨識':'Start recognition','完成匯入':'Imported','仍待核對 · 未帶入':'Awaiting review · not imported','無法辨識 · 未帶入':'Unrecognised · not imported','未選取':'Not selected','已選取':'Selected','請選擇':'Select','選填':'Optional','核對辨識結果':'Review recognition results','已核對，準備套用':'Reviewed, ready to apply','確認並套用':'Confirm and apply','文件上傳與識別':'Document upload & recognition','辨識結果及來源':'Recognition results & sources','必交文件檢查':'Required document checks','收費類型':'Pricing type','適用範圍':'Scope','費率（%）':'Rate (%)','每筆費用（HKD）':'Per-transaction fee (HKD)','保底（HKD）':'Minimum (HKD)','封頂（HKD）':'Maximum (HKD)','本地卡':'Local cards','跨境卡':'Cross-border cards','優惠費率':'Preferential rate','產品配置':'Product configuration','特計商戶':'Special merchant','開通':'Enable','卡組織':'Card network','特計商戶類型':'Special merchant type','收單':'Acquiring','線下掃碼支付':'In-store QR payments','線上掃碼支付':'Online QR payments','帳戶驗證':'Account verification','驗證':'Verify','返回登入頁面':'Back to sign in','最高管理員':'Administrator','基本管理員':'Manager','主代理商':'Primary agent','次代理商':'Sub-agent'
};
Object.assign(AZURE_EN,{
 '確認驗證碼':'Confirm code','手機識別驗證碼（Demo）':'Mobile verification code (Demo)','手機完成後顯示的 6 位數':'6-digit code displayed on your phone','示例驗證碼：':'Demo code: ',
 '模擬手機識別完成（顯示驗證碼）':'Simulate phone completion (show code)','等待手機識別完成及驗證碼確認。':'Waiting for phone completion and code confirmation.','已收到手機識別結果，請輸入驗證碼以完成認證。':'Phone result received. Enter the code to complete the demo.',
 '請輸入完整的 6 位數驗證碼。':'Enter the complete 6-digit code.','驗證碼不正確，請核對手機顯示的驗證碼。':'Incorrect code. Check the code displayed on your phone.','資料已變更或連結已失效，請重新開始識別。':'Information changed or the link expired. Start again.','驗證碼已確認，已完成 KTC 認證示例':'Code confirmed. KTC demo completed.',
 'KTC／KYC 手機實拍 Demo':'KTC / KYC mobile photo demo','手機實拍 · KTC／KYC Demo':'Mobile photo capture · KTC / KYC Demo','人像拍攝':'Take a selfie','拍攝人像':'Capture selfie','拍攝身分證':'Capture ID photo','開啟／重試相機':'Open / retry camera','切換前後鏡頭':'Switch camera','同意並開始拍照':'Agree and open camera',
 '核對身分證照片':'Review ID photo','核對人像照片':'Review selfie','確認並拍攝人像':'Confirm and take selfie','重新拍攝身分證':'Retake ID photo','重新拍攝人像':'Retake selfie','確認照片並取得驗證碼':'Confirm photo and get code','取消並清除照片':'Cancel and clear photos','照片已確認（Demo）':'Photos confirmed (Demo)',
 '照片完整且清晰，我已核對':'I have checked that the photo is complete and clear','人像清晰，我確認使用此照片演示':'The selfie is clear. Use this photo for the demo','我了解照片的本機暫存方式，並同意開啟相機進行實拍 Demo':'I understand local-only photo storage and agree to open the camera for this demo',
 '無法開啟預覽？使用系統相機／照片':'No preview? Use the system camera / photos','拍照或選擇照片':'Take or choose a photo','照片只在此手機頁面暫存 · 每份上限 10 MB':'Photos stay in this phone page only · 10 MB maximum each',
 '需由你允許相機權限。照片只暫存在此頁，不上傳、不寫入草稿；離開或重新整理會清除。不執行正式身分、人臉比對或活體驗證。':'Camera permission is required. Photos remain only in this page, are not uploaded or saved to drafts, and are cleared when you leave or reload. No identity, face matching or liveness verification is performed.',
 '僅供拍攝流程演示；正式證件辨識、人臉比對及活體驗證尚未串接。':'Photo-flow demo only. Document recognition, face matching and liveness verification are not connected.',
 '請正視鏡頭，將臉部放入框內。這是實拍 Demo，不執行人臉比對或活體驗證。':'Look at the camera with your face inside the guide. This captures a real photo but does not perform face matching or liveness checks.',
 '請將完整證件四角放入框內，避免反光。此步只拍照與人工核對，不會自動辨識證件內容。':'Place all four corners inside the guide and avoid glare. This step captures a photo for manual review, without document recognition.',
 '請確認照片完整、清晰且無反光。本 Demo 沒有辨識或填入證件欄位。':'Check that the photo is complete, clear and glare-free. No document fields are recognised or filled by this demo.',
 '請確認臉部清晰且未被遮擋。本 Demo 不執行人臉比對或活體驗證。':'Check that your face is clear and unobstructed. No face matching or liveness check is performed.',
 '請返回電腦，輸入以下驗證碼並按「確認驗證碼」，才會顯示識別成功。':'Return to your computer, enter this code and select Confirm code to show the success dialog.',
 '照片已從本頁釋放，沒有上傳。這不代表通過正式 KYC 認證。':'Photos have been cleared without upload. This does not represent a verified KYC result.',
 '請允許相機權限，或使用下方系統相機。':'Allow camera access or use the system camera below.','正在請求相機權限…':'Requesting camera access…','相機已開啟，只會在你按下拍攝時擷取一張照片。':'Camera ready. A photo is captured only when you select Capture.','尚未拍攝照片。':'No photo captured yet.',
 '相機權限未開啟。請在瀏覽器設定允許相機後重試，或使用系統相機。':'Camera access denied. Allow access in browser settings and retry, or use the system camera.','找不到可用相機，請改用有相機的手機。':'No camera found. Use a phone with a camera.','請使用 10 MB 以下的照片。':'Choose a photo smaller than 10 MB.','照片無法讀取或尺寸過大，請重新拍照或改用 JPG／PNG。':'Cannot read the photo or it is too large. Retake it or use JPG / PNG.',
 '相機已暫停，請按「開啟／重試相機」。':'Camera paused. Select Open / retry camera.','已導入並核對身分證資訊，只需拍攝人像。':'Imported ID details have been reviewed. Only a selfie is needed.','手機拍攝身分證 → 預覽核對 → 前鏡頭拍攝人像。':'Take an ID photo → review it → take a front-camera selfie.'
});
