// Internal review console. Local, synthetic demo only — never an authorization boundary.
const IR = {query:'',scope:'全部欄位',status:'Pending',page:1,size:5,selected:null,tab:'fields',doc:0,role:'L2',notes:{},checked:{},pending:null,fail:false};
const irStages={L1:'L1 初審／抽檢',L2:'L2 風控覆審',L3:'L3 終審',Done:'已核准／待同步',MoreInfo:'待補資料',Rejected:'已拒絕'};
const irReasons=['BR 圖片模糊／文件不完整','地址與門店照片不符','結算帳戶名稱不一致','缺少商戶與消費者 T&C（141601）','NAR1／NNC1 缺少或過期（141101）','缺少近 3 個月銀行帳單（141301）','MCC 與實際經營不符','其他（請說明）'];
const irDocTypes=[['商業登記證 BR','140101'],['NAR1 周年申報表','141101'],['負責人身份證正面','100301'],['結算銀行對帳單','140401'],['門店照片','101401'],['近 3 個月銀行帳單','141301']];
const irOldSidebar=sidebar;
sidebar=function(page){const item=can(7)?`<a class="nav-link ${page==='internal-review'?'active':''}" href="#/internal-review"><img class="ir-nav-icon" src="04d0d.svg" alt="">內審控制台</a>`:'';return irOldSidebar(page).replace('<div class="nav-divider">',item+'<div class="nav-divider">');};
function irBase(r){
  const index=Number(String(r['公司 MID']).replace(/\D/g,''))||0,level=['B','C','A'][index%3];
  // Stable IDs, not queue positions: filtering/approving another case must not change this case.
  const stage=r.status==='Pending'?(r['公司 MID']==='M000531'?'L2':r['公司 MID']==='M000826'?'L3':index%3===2?'L1':index%2?'L1':'L2'):r.status==='MoreInfo'?'MoreInfo':r.status==='Rejected'?'Rejected':'Done';
  const normalized=stage==='L3'?'C':stage==='L2'&&level==='A'?'B':level;
  return {stage,tier:normalized,score:{A:12,B:33,C:68}[normalized],appId:'APP-20260924-'+String(index+1).padStart(4,'0'),revision:0,trail:[{time:'2026/09/24 09:12',actor:r.owner||'示例代理商',message:'提交申請（示例）'},{time:'2026/09/24 09:20',actor:'系統 Demo',message:'完成示例風險評分及 OCR 欄位核對'}],...r.internalReview};
}
const irRiskName=c=>({A:'低風險',B:'中風險',C:'高風險'}[c.tier]);
const irSLA=r=>rows.indexOf(r)%9===5?{text:'已逾時 3 小時',overdue:true}:{text:'剩餘 '+(3+rows.indexOf(r)%9)+' 小時',overdue:false};
const irVisible=()=>can(7)?scopedRows():[];
const irCurrent=()=>irVisible().find(r=>r['公司 MID']===IR.selected);
const irSearchKeys=['客戶中文名稱','客戶英文名稱','公司 MID','BR','DBA no.','客戶聯繫人','銀行名稱','銀行帳號','主代理商代碼','次代理商代碼'];
function irFiltered(){const q=IR.query.trim().toLocaleLowerCase();return irVisible().filter(r=>(IR.status==='all'||r.status===IR.status)&&(!q||(IR.scope==='全部欄位'?irSearchKeys:[IR.scope]).some(k=>String(k==='銀行帳號'?(can(5)?r.bank:r[k]):r[k]||'').toLocaleLowerCase().includes(q))));}
function irStage(r){return ['Pending','MoreInfo','Rejected'].includes(r.status)?irStages[r.status==='Pending'?irBase(r).stage:r.status]:statusNames[r.status]||r.status;}
function irOptions(list,value){return list.map(x=>{const [v,l]=Array.isArray(x)?x:[x,x];return `<option value="${esc(v)}" ${String(value)===String(v)?'selected':''}>${esc(l)}</option>`}).join('');}
function irQueueBadges(r){const c=irBase(r),tone=c.stage==='L3'?'red':r.status==='Rejected'?'red':r.status==='MoreInfo'?'amber':['Approved','Synced'].includes(r.status)?'green':'neutral';return `<span class="ir-badges"><span class="pill ir-badge ${ {A:'green',B:'blue',C:'amber'}[c.tier]}" aria-label="${c.tier} ${irRiskName(c)}，${c.score} 分">${c.tier} · ${c.score} 分</span><span class="pill ir-badge ir-stage-badge ${tone}">${esc(irStage(r))}</span></span>`;}
function irQueue(list){
 const pages=Math.max(1,Math.ceil(list.length/IR.size));IR.page=Math.max(1,Math.min(IR.page,pages));const shown=list.slice((IR.page-1)*IR.size,IR.page*IR.size);
 return `<section class="ir-queue" aria-labelledby="ir-queue-title"><h2 id="ir-queue-title">待審隊列</h2><p class="hint" id="ir-count" aria-live="polite">顯示 ${list.length?(IR.page-1)*IR.size+1:0}–${Math.min(IR.page*IR.size,list.length)} 間，共 ${list.length} 間公司</p><div class="ir-queue-list">${shown.map(r=>{const c=irBase(r),id=r['公司 MID'];return `<button class="ir-case ${id===IR.selected?'selected':''}" data-action="ir-select" data-mid="${esc(id)}" aria-pressed="${id===IR.selected}"><strong>${esc(r['客戶中文名稱'])}</strong><small>${esc(c.appId)} · ${esc(id)}</small>${irQueueBadges(r)}<small class="${irSLA(r).overdue?'error':''}">${irSLA(r).text} · ${esc(r['主代理商代碼'])}</small></button>`}).join('')}</div><div class="ir-pages">${btn('上一頁','ir-page','',`data-page="${IR.page-1}" ${IR.page===1?'disabled':''}`)}<span aria-live="polite">${IR.page} / ${pages}</span>${btn('下一頁','ir-page','',`data-page="${IR.page+1}" ${IR.page===pages?'disabled':''}`)}</div><label class="ir-size">每頁 <select id="ir-size">${irOptions([5,10,20,50].map(n=>[n,n+' 間公司']),IR.size)}</select></label><p class="hint">逾時案件優先跟進。切換頁面不會變更目前選中的案件。</p></section>`;
}
function irDocument(r,index=IR.doc){
 const [name,code]=irDocTypes[index]||irDocTypes[0],id=r['公司 MID'],values=index===0?[['Business name',r['客戶英文名稱']],['BR Number',r.BR],['Valid until',r['BR 有效期']],['Business nature',r['行業類型']]]:index===1?[['公司名稱',r['客戶中文名稱']],['周年申報編號','DEMO-NAR1-'+id],['申報日期','2026/09/01']]:index===2?[['持有人',r['客戶聯繫人']],['證件編號','DEMO（遮蔽）'],['文件性質','示例文件，非真實身份證']]:index===4?[['門店名稱',r['客戶中文名稱']],['營業地區',r['地區']],['門店紀錄','Demo 文件佔位，非真實照片']]:[['帳戶名稱',r['客戶英文名稱']],['銀行名稱',r['銀行名稱']],['帳號',can(5)?r.bank:r['銀行帳號']],['結單期',index===5?'2026/06–2026/08':'2026/08']];
 return `<article class="ir-document"><h3>${esc(name)}</h3><small>DEMO 文件預覽 · ${code}</small><dl>${values.map(([k,v])=>`<div><dt>${esc(k)}</dt><dd>${esc(v||'未提供')}</dd></div>`).join('')}</dl><p class="hint">合成示例，不是商戶原始文件或真實 OCR。</p></article>`;
}
function irDocuments(r){return `<section class="card ir-docs"><h2>上傳文件</h2><div class="ir-document-list">${irDocTypes.map(([label,code],i)=>`<button class="ir-doc ${IR.doc===i?'selected':''}" data-action="ir-document" data-index="${i}" aria-pressed="${IR.doc===i}"><span aria-hidden="true">▤</span><span><strong>${label}</strong><small>${code}</small></span></button>`).join('')}</div><div id="ir-document-preview">${irDocument(r)}</div>${btn('放大預覽','ir-zoom')}</section>`;}
function irFields(r){const c=irBase(r),diff=c.tier!=='A',addr='Shop '+(100+rows.indexOf(r))+', 700 Nathan Road',bank=can(5)?r.bank:r['銀行帳號'];
 const values=[['中文名稱',r['客戶中文名稱'],r['客戶中文名稱']],['英文名稱',r['客戶英文名稱'],diff?r['客戶英文名稱'].replace(/LIMITED$/,'LTD'):r['客戶英文名稱']],['BR 號碼',r.BR,r.BR],['證書有效期',r['BR 有效期'],r['BR 有效期']],['營業地址（英文）',addr,diff?addr.replace('Road','Rd'):addr],['帳戶名稱',r['客戶英文名稱'],r['客戶英文名稱']],['銀行帳號',bank,bank],['MCC',r['MCC 行業代碼']+' · '+r['行業類型'],'無 OCR 來源']];
 return `<div class="ir-compare-scroll"><table class="ir-compare"><thead><tr><th scope="col">欄位</th><th scope="col">商戶填報</th><th scope="col">OCR / 外部核驗</th></tr></thead><tbody>${values.map(([key,a,b],i)=>`<tr class="${i!==7&&a!==b?'ir-diff':''}"><th scope="row">${key}${i!==7&&a!==b?'<small>資料差異</small>':''}</th><td>${esc(a||'未提供')}</td><td>${esc(b||'未提供')}</td></tr>`).join('')}</tbody></table></div><div class="ir-warning">${diff?'2 項資料不一致，請核實為填寫錯誤或實際不符後再審批。':'本示例未檢出資料差異，仍須核對原始文件及必填資料。'}</div>`;
}
function irRisk(r){const c=irBase(r),parts=c.tier==='C'?[['行業風險',12],['開通 CNP 產品',15],['OCR / 外部核驗差異',10],['新成立公司',8],['跨境業務',15],['其他風險因子',8]]:c.tier==='B'?[['行業風險',8],['開通 CNP 產品',10],['OCR / 外部核驗差異',10],['文件完整度',0],['開業未滿 12 個月',5]]:[['行業風險',4],['交易規模',3],['新合作商戶',5]];
 return `<h3>風控評分 ${c.score} / 100 · ${c.tier} ${irRiskName(c)}</h3><div class="ir-risk-parts">${parts.map(([k,n])=>`<div><span>${k}</span><strong>+${n}</strong></div>`).join('')}</div><h3>按風控級別處置</h3><dl class="ir-treatment">${[['審批路徑',c.tier==='A'?'L1 自動初審，抽檢 10% → 送 OATS':c.tier==='B'?'L1 全審 → L2 風控覆審 → 送 OATS':'L1 全審 → L2 風控覆審 → L3 終審 → 送 OATS'],['結算週期',c.tier==='C'?'T7':c.tier==='B'?'T2':'T1'],['保證金',c.tier==='C'?'10% · 90 天釋放':c.tier==='B'?'收單 5% · 30 天釋放':'無'],['限額',c.tier==='C'?'單筆 10,000／每月 300,000':c.tier==='B'?'單筆 30,000／每月 1,000,000':'單筆 50,000／每月 2,000,000'],['目標時效',c.tier==='C'?'T+2':c.tier==='B'?'T+1':'4 小時']].map(([k,v])=>`<dt>${k}</dt><dd>${v}</dd>`).join('')}</dl><p class="hint">Demo 規則，並非正式風控政策；不會真正自動審批或傳送 OATS。</p>`;
}
function irTrail(r){return `<h3>審批紀錄（唯讀）</h3><ol class="ir-trail">${irBase(r).trail.map(t=>`<li><strong>${esc(t.time)} · ${esc(t.actor)}</strong><p>${esc(t.message)}</p></li>`).join('')}</ol><p class="hint">介面只允許新增紀錄，不提供刪改。資料儲存在本瀏覽器，並非正式不可竄改稽核系統。</p>`;}
function irAllowed(r,stage=irBase(r).stage){return can(7)&&r.owner!==BO.user.id&&r.status==='Pending'&&stage===IR.role&&irBase(r).stage===stage;}
function irDetail(r){const id=r['公司 MID'],c=irBase(r),own=r.owner===BO.user.id,allowed=irAllowed(r);
 return `<section class="card ir-detail" aria-labelledby="ir-company"><h2 id="ir-company">${esc(r['客戶中文名稱'])}</h2><p class="hint">${esc(c.appId)} · ${esc(id)} · ${esc(r['客戶英文名稱'])} · MCC ${esc(r['MCC 行業代碼'])}</p><p class="ir-case-meta">${c.tier} ${irRiskName(c)} · ${c.score} 分 ｜ 結算 ${c.tier==='C'?'T7':c.tier==='B'?'T2':'T1'} ｜ ${esc(r['主代理商代碼'])} ｜ <span class="${irSLA(r).overdue?'error':''}">${irSLA(r).text}</span></p><div class="ir-tabs" role="tablist" aria-label="案件內容">${[['fields','字段核對'],['risk','風控評分明細'],['trail','審批紀錄']].map(([key,label])=>btn(label,'ir-tab',IR.tab===key?'primary':'',`data-tab="${key}" role="tab" id="ir-tab-${key}" aria-controls="ir-tab-panel" aria-selected="${IR.tab===key}"`)).join('')}</div><div id="ir-tab-panel" role="tabpanel" aria-labelledby="ir-tab-${IR.tab}">${IR.tab==='risk'?irRisk(r):IR.tab==='trail'?irTrail(r):irFields(r)}</div><div class="ir-approval"><label class="check"><input id="ir-checked" type="checkbox" ${IR.checked[id]?'checked':''} ${!allowed?'disabled':''}>已逐項核對差異及原始文件</label><div class="field"><label for="ir-note">審批備註${c.stage==='L3'?' *':''}</label><textarea id="ir-note" rows="2" maxlength="1000" ${!allowed?'disabled':''} placeholder="記錄核對依據；高風險終審必須填寫理由">${esc(IR.notes[id]||'')}</textarea></div><div class="ir-actions">${btn('駁回／要求補件','ir-reject','',!allowed?'disabled':'')}${[['L1','初審通過 L1'],['L2','覆審通過 L2'],['L3','終審放行 L3']].map(([stage,label])=>btn(label,'ir-approve',irAllowed(r,stage)?'review-button':'',`data-stage="${stage}" ${!irAllowed(r,stage)?'disabled':''}`)).join('')}</div><p class="hint">${own?'填單人不得審批自己的申請。':r.status!=='Pending'?'此案件為「'+esc(irStage(r))+'」，目前唯讀。':allowed?'目前僅可執行 '+IR.role+'。駁回需選擇原因並補充說明。':'目前身份 '+IR.role+' 與案件階段 '+c.stage+' 不符，不能審批。'}</p><p class="error" id="ir-action-error" role="alert"></p></div></section>`;
}
function irConsole(){if(!can(7))return `${heading('內審控制台','')}<div class="readonly-banner">權限不足，不能查看內審公司、文件或審批紀錄。請聯絡管理員授權。</div>`;
 const all=irVisible(),list=irFiltered();if(!IR.selected||!irCurrent())IR.selected=(list[0]||{} )['公司 MID']||null;const selected=irCurrent(),pending=all.filter(r=>r.status==='Pending'),events=all.flatMap(r=>(r.internalReview?.trail||[]).filter(t=>t.local)),today=new Date().toLocaleDateString('zh-HK');
 return `${heading('內審控制台','初審 L1 ／ 風控覆審 L2 ／ 終審 L3　｜　填單人不可審批自己的申請；所有操作均保留紀錄。')}<section class="card ir-overview">${[['待處理',pending.length+' 間'],['已逾時',pending.filter(r=>irSLA(r).overdue).length+' 間'],['今日已審',events.filter(t=>t.day===today).length+' 間'],['首次駁回率',events.length?(100*events.filter(t=>t.reject).length/events.length).toFixed(1)+'%':'—']].map(([k,v])=>`<div><small>${k}</small><strong>${v}</strong></div>`).join('')}<label>目前審批身份（Demo）<select id="ir-role">${irOptions([['L1','初審 L1'],['L2','風控覆審 L2'],['L3','終審 L3']],IR.role)}</select><small>${esc(BO.user.name)} · 切換僅用於展示，不是正式授權</small></label></section><form class="card search-grid ir-search" id="ir-search-form"><div><label for="ir-query">跨欄位搜尋</label><input id="ir-query" value="${esc(IR.query)}" placeholder="搜尋公司名稱、MID、BR、DBA、聯繫人、銀行名稱或帳號"></div><div><label for="ir-scope">搜尋範圍</label><select id="ir-scope">${irOptions(['全部欄位',...irSearchKeys],IR.scope)}</select></div><div><label for="ir-status">商戶狀態</label><select id="ir-status">${irOptions([['all','全部狀態'],['Pending','待審核'],['MoreInfo','待補資料'],['Approved','通過審核'],['Rejected','已拒絕'],['Synced','已同步']],IR.status)}</select></div>${btn('重設','ir-reset')}<button class="primary" type="submit">搜尋</button></form>${list.length?`<div class="ir-workspace">${irQueue(list)}${selected?irDocuments(selected)+irDetail(selected):''}</div>`:`<section class="card empty"><h2>找不到符合條件的公司</h2><p id="ir-count">共 0 間公司。請變更關鍵字、搜尋範圍或商戶狀態。</p>${btn('重設搜尋','ir-reset','primary')}</section>`}<div class="ir-demo-note"><span>240+ 筆假資料 · 文件及 OCR 為合成示例，審批僅留在本瀏覽器，不寄電郵或傳送 OATS。</span><label><input id="ir-fail" type="checkbox" ${IR.fail?'checked':''}>模擬儲存失敗</label></div>`;
}
const irPreviousRender=render;
render=function(){if(BO.user&&route().page==='internal-review'){closeColumn();$('#app').innerHTML=`${sidebar('internal-review')}${btn('選單','mobile-menu','mobile-menu')}<main class="main"><div class="content ir-console">${irConsole()}</div></main>`;$('#ir-search-form')?.addEventListener('submit',e=>{e.preventDefault();actions['ir-search']()});return;}irPreviousRender();};
function irCapture(){const r=irCurrent();if(r){const id=r['公司 MID'];if($('#ir-note'))IR.notes[id]=$('#ir-note').value;if($('#ir-checked'))IR.checked[id]=$('#ir-checked').checked;}}
function irError(message){const target=$('#ir-action-error');if(target)target.textContent=message;else toast(message);}
function irOpenDecision(type){irCapture();const r=irCurrent();if(!r||!irAllowed(r))return deny();const c=irBase(r),id=r['公司 MID'];if(type==='approve'&&!IR.checked[id])return irError('請先勾選「已逐項核對差異及原始文件」。');
 IR.pending={mid:id,type,stage:c.stage,revision:c.revision,decision:'MoreInfo',reason:'',note:IR.notes[id]||''};irDecisionForm();}
function irDecisionForm(){const p=IR.pending,r=accessibleRow(p?.mid);if(!r||!can(7))return deny();const final=p.type==='approve'&&p.stage==='L3';modal(p.type==='reject'?'駁回／要求補件':final?'高風險終審確認':'確認審批結果',`<p><strong>${esc(r['客戶中文名稱'])}</strong> · ${esc(irBase(r).appId)}</p>${p.type==='reject'?`<div class="field"><label for="ir-decision">處理方式</label><select id="ir-decision">${irOptions([['MoreInfo','要求補件'],['Rejected','駁回申請']],p.decision)}</select></div><div class="field"><label for="ir-reason">快速原因 *</label><select id="ir-reason">${irOptions([['','請選擇原因'],...irReasons],p.reason)}</select></div>`:`<p>確認通過 ${p.stage}？${p.stage==='L1'&&irBase(r).tier!=='A'?'將轉交 L2 風控覆審。':p.stage==='L2'&&irBase(r).tier==='C'?'將轉交 L3 終審。':'將標記為通過審核，等待同步。'}</p>`}<div class="field"><label for="ir-decision-note">${final?'終審理由 *':p.type==='reject'?'補充說明 *':'審批備註'}</label><textarea id="ir-decision-note" rows="4" maxlength="1000" placeholder="${final?'請說明接受風險的依據、管控條件及審查結論':'請輸入核對依據或需要商戶補正的內容'}">${esc(p.note)}</textarea></div><p class="hint">僅更新此 Demo；不會寄出通知或向正式 OATS 傳送資料。</p><p id="ir-decision-error" class="error" role="alert"></p>`,btn('取消','close')+btn(p.type==='reject'?'確認處理':'確認通過','ir-save',p.type==='reject'?'primary':'review-button'));}
Object.assign(actions,{
 'ir-select':el=>{if(!can(7))return deny();irCapture();if(!accessibleRow(el.dataset.mid))return deny();IR.selected=el.dataset.mid;IR.doc=0;IR.tab='fields';render();},
 'ir-search':()=>{if(!can(7))return deny();irCapture();IR.query=$('#ir-query').value;IR.scope=$('#ir-scope').value;IR.status=$('#ir-status').value;IR.page=1;IR.selected=null;IR.doc=0;render();},
 'ir-reset':()=>{Object.assign(IR,{query:'',scope:'全部欄位',status:'Pending',page:1,selected:null,doc:0});render();},
 'ir-page':el=>{irCapture();IR.page=+el.dataset.page;render();},
 'ir-tab':el=>{if(!can(7))return deny();irCapture();IR.tab=['fields','risk','trail'].includes(el.dataset.tab)?el.dataset.tab:'fields';render();},
 'ir-document':el=>{if(!can(7))return deny();irCapture();IR.doc=Math.max(0,Math.min(5,+el.dataset.index||0));render();},
 'ir-zoom':()=>{const r=irCurrent();if(!r)return deny();modal('文件預覽 · '+irDocTypes[IR.doc][0],`<div class="ir-zoom">${irDocument(r)}</div>`,btn('關閉','close','primary'));},
 'ir-reject':()=>irOpenDecision('reject'),'ir-approve':el=>{const r=irCurrent();if(!r||!irAllowed(r,el.dataset.stage))return deny();irOpenDecision('approve');},
 'ir-save':()=>{
  const p=IR.pending,r=accessibleRow(p?.mid),error=$('#ir-decision-error');if(!p||!r||!irAllowed(r,p.stage))return deny();p.note=$('#ir-decision-note').value.trim();IR.notes[p.mid]=p.note;if(p.type==='reject'){p.reason=$('#ir-reason').value;p.decision=$('#ir-decision').value;}
  if(p.type==='reject'&&(!irReasons.includes(p.reason)||!p.note)){error.textContent=!p.reason?'請先選擇拒絕／補件原因。':'請填寫補充說明。';return;}
  if(p.stage==='L3'&&p.type==='approve'&&!p.note){error.textContent='高風險終審必須填寫理由，不能留白。';return;}
  if(p.type==='approve'&&!IR.checked[p.mid]){error.textContent='請返回核對原始文件。';return;}
  if(IR.fail){error.textContent='模擬儲存失敗：原狀態未變更，備註已保留。請取消後關閉失敗模擬再重試。';return;}
  const before=structuredClone(r),c=irBase(r);if(c.revision!==p.revision){error.textContent='案件已被更新，請重新載入核對。';return;}
  const nextStage=p.type==='reject'?p.decision:p.stage==='L1'&&c.tier!=='A'?'L2':p.stage==='L2'&&c.tier==='C'?'L3':'Done';
  const now=new Date(),trail={time:now.toLocaleString('zh-HK',{hour12:false}),day:now.toLocaleDateString('zh-HK'),actor:BO.user.name+' · '+IR.role,message:(p.type==='reject'?statusNames[p.decision]+' · '+p.reason:'通過 '+p.stage+' → '+irStages[nextStage])+(p.note?'；'+p.note:''),local:true,reject:p.type==='reject'};
  r.internalReview={...c,stage:nextStage,revision:c.revision+1,trail:[...c.trail,trail]};r.status=nextStage==='Done'?'Approved':['MoreInfo','Rejected'].includes(nextStage)?nextStage:'Pending';r.reviewReason=p.reason;r.reviewNote=p.note;if(nextStage==='MoreInfo')r.missing=[p.reason,p.note];
  const oldAudit=[...BO.audit],oldNotice=state.noticeCount;audit('內審 '+r['客戶中文名稱']+' · '+trail.message);state.noticeCount++;
  if(!persistDemo()){for(const k of Object.keys(r))delete r[k];Object.assign(r,before);BO.audit=oldAudit;state.noticeCount=oldNotice;error.textContent='儲存失敗，原狀態未變更。請檢查瀏覽器儲存設定後再試。';return;}
  IR.notes[p.mid]='';IR.checked[p.mid]=false;IR.pending=null;render();modal('審批已更新（Demo）',`<div class="notice">${esc(r['客戶中文名稱'])}：${esc(irStage(r))}</div><p>隊列及商戶管理已同步更新，審批紀錄已新增。</p><p class="hint">僅儲存在本瀏覽器，未寄送電郵或傳送 OATS。</p>`,btn('完成','close','primary'));
 }
});
document.addEventListener('change',e=>{const t=e.target;if(t.id==='ir-size'){irCapture();IR.size=[5,10,20,50].includes(+t.value)?+t.value:5;IR.page=1;render();}if(t.id==='ir-role'){irCapture();IR.role=['L1','L2','L3'].includes(t.value)?t.value:'L2';render();}if(t.id==='ir-fail')IR.fail=t.checked;});
document.addEventListener('input',e=>{if(e.target.id==='ir-note'&&IR.selected)IR.notes[IR.selected]=e.target.value;});
window.addEventListener('hashchange',()=>{if(!BO.user){IR.pending=null;IR.notes={};IR.checked={};IR.selected=null;}});
