const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs');
const {completeOTP,completeKTC}=require('./test-azure-helpers.cjs');
const base=(process.env.DEMO_URL||'http://127.0.0.1:4321').replace(/\/(backoffice|external|index)\.html.*$/,'');
const click=(p,a)=>p.locator('[data-action="'+a+'"]').first().click();
async function emailOTP(p){for(let i=0;i<6;i++)await p.locator('[data-otp="'+i+'"]').fill(String(i+1));await click(p,'verify');}
async function login(p,target){await p.goto(base+'/'+target+'.html#/login');if(target==='backoffice'){await click(p,'pick-role');await click(p,'bo-login');}else{await p.locator('#authEmail').fill('azure.demo@example.com');await click(p,'login');await emailOTP(p);}await completeOTP(p);}
async function form(p,target,step){await p.evaluate(({target,step})=>location.hash='/'+(target==='external'?'form':'application')+'/'+step,{target,step});await p.waitForFunction(step=>document.querySelector('[data-step].active')?.dataset.step===String(step),step);await p.waitForSelector(step==='ktc'?'.ktc-panel':'.v2-form');}
function pdf(lines){const stream='BT /F1 12 Tf 30 780 Td '+lines.map((s,i)=>(i?'0 -22 Td ':'')+'('+s.replace(/[()\\]/g,'\\$&')+') Tj').join('\n')+' ET',objects=['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [3 0 R] /Count 1 >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>','<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>','<< /Length '+Buffer.byteLength(stream)+' >>\nstream\n'+stream+'\nendstream'];let text='%PDF-1.4\n',offsets=[0];objects.forEach((o,i)=>{offsets.push(Buffer.byteLength(text));text+=(i+1)+' 0 obj\n'+o+'\nendobj\n';});const xref=Buffer.byteLength(text);text+='xref\n0 6\n0000000000 65535 f \n'+offsets.slice(1).map(n=>String(n).padStart(10,'0')+' 00000 n \n').join('')+'trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n'+xref+'\n%%EOF';return Buffer.from(text);}
(async()=>{
 const browser=await chromium.launch({headless:true,...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{})}),errors=[],checks=[];
 try{
 for(const target of ['backoffice','external']){
  const context=await browser.newContext({viewport:{width:1600,height:1000}}),p=await context.newPage();p.on('pageerror',e=>errors.push(target+': '+e.message));
  await p.goto(base+'/'+target+'.html#/login');
  if(target==='backoffice'){await click(p,'pick-role');await click(p,'bo-login');}else{await p.locator('#authEmail').fill('azure.demo@example.com');await click(p,'login');await emailOTP(p);}
  await p.locator('#azure-code').fill('000000');await click(p,'azure-auth-check');assert.match(await p.locator('#azure-auth-error').innerText(),/不正確/);
  assert.equal(await p.locator('.metrics,.header').count(),0);await completeOTP(p);
  await form(p,target,1);assert.equal(await p.locator('.step').count(),7);assert.equal(await p.locator('.step').nth(1).getAttribute('data-step'),'ktc');
  if(target==='backoffice'){
   const g=await p.evaluate(()=>({logo:document.querySelector('.sidebar .brand').getBoundingClientRect().bottom,tab:document.querySelector('.tabs').getBoundingClientRect().bottom,invites:document.querySelectorAll('#v2-application-status>.agency-invitation').length,children:[...document.querySelectorAll('.sidebar .nav-link')].map(n=>n.textContent.trim())}));
   assert.equal(g.logo,56);assert.equal(g.tab,57);assert.equal(g.invites,1);assert(g.children.some(t=>t.includes('內審控制台')));
   await p.screenshot({path:'qa-azure-step1.png'});
  }
  await click(p,'next');await p.waitForSelector('.ktc-panel');await click(p,'ktc-review');assert(await p.locator('[data-action="ktc-confirm-id"]').isDisabled());await click(p,'ktc-review-back');
  await click(p,'ktc-start');assert.equal(await p.locator('.azure-qr svg').count(),1);
  const href=await p.locator('.ktc-link').getAttribute('href');assert.match(href,/\/ktc-mobile\/[a-f0-9-]{36}\/full\/\d+/);assert(!href.includes('example.com'));
  const mobile=await context.newPage();mobile.on('pageerror',e=>errors.push('mobile: '+e.message));await mobile.setViewportSize({width:390,height:844});await mobile.goto(href);
  await click(mobile,'ktc-mobile-start');assert.equal(await mobile.locator('[data-action="ktc-mobile-photo"]').count(),0);await mobile.locator('#ktc-consent').check();await click(mobile,'ktc-mobile-start');await click(mobile,'ktc-mobile-photo');await mobile.locator('#ktc-mobile-confirm').check();await click(mobile,'ktc-mobile-face');await click(mobile,'ktc-mobile-failure');await click(mobile,'ktc-mobile-retry');await mobile.screenshot({path:'qa-azure-mobile-face.png'});await click(mobile,'ktc-mobile-success');
  await p.locator('#modal[open]').waitFor();assert.equal(await p.locator('#modal-title').innerText(),'識別成功');assert((await p.evaluate(()=>AllinPayDemo.getKTC())).passed);await p.locator('#modal [data-action="ktc-next"]').click();await p.waitForSelector('[data-field="merchantName"]');await mobile.close();
  await p.locator('[data-field="directors[0].name"]').fill('CHANGED DEMO');assert.equal((await p.evaluate(()=>AllinPayDemo.getKTC())).passed,false);
  await form(p,target,'ktc');await click(p,'ktc-start');await click(p,'ktc-expire');assert.equal(await p.locator('[data-action="ktc-demo-success"]').count(),0);assert(await p.locator('.ktc-panel [data-action="ktc-next"]').isDisabled());await click(p,'ktc-cancel');
  await form(p,target,1);await click(p,'v2-ocr');await p.locator('#document-batch-files').setInputFiles({name:'SYNTHETIC-DIRECTOR-ID.pdf',mimeType:'application/pdf',buffer:pdf(["Director's Identity Card",'Name: DEMO USER','Identity Card Number: Z123456(0)','Date of Birth: 1985-06-15'])});await click(p,'document-recognize');await p.waitForSelector('.batch-assignments',{timeout:130000});
  assert.equal(await p.locator('.batch-candidate').count(),3,'Name, identity number and birth date extracted from PDF');const id=await p.locator('[data-document-destination] option').evaluateAll(es=>es.find(e=>e.textContent==='董事身份證明')?.value);assert(id,'Director ID upload slot');await p.locator('[data-document-destination]').selectOption(id);for(const n of await p.locator('[data-document-select]').all())await n.check();for(const n of await p.locator('[data-document-replace]').all())await n.check();await p.locator('#batch-reviewed').check();await click(p,'document-ready');await click(p,'document-apply');await p.locator('#modal [data-action="close"]').first().click();
  await form(p,target,'ktc');assert.equal((await p.evaluate(()=>AllinPayDemo.getKTC())).canSkipPhoto,false);await click(p,'ktc-review');assert((await p.evaluate(()=>AllinPayDemo.getKTC())).imported,'ID import was not applied');await p.locator('#ktc-id-confirm').check();await click(p,'ktc-confirm-id');assert.equal((await p.evaluate(()=>AllinPayDemo.getKTC())).canSkipPhoto,true);await click(p,'ktc-start');assert.match(await p.locator('.ktc-link').getAttribute('href'),/\/face\//);
  const phoneContext=await browser.newContext({viewport:{width:390,height:844}}),phone=await phoneContext.newPage();await phone.goto(await p.locator('.ktc-link').getAttribute('href'));await phone.locator('#ktc-consent').check();await click(phone,'ktc-mobile-start');assert.equal(await phone.locator('[data-action="ktc-mobile-photo"]').count(),0);await click(phone,'ktc-mobile-success');const returnCode=await phone.locator('.ktc-check strong').innerText();await p.locator('#ktc-return-code').fill(returnCode);await click(p,'ktc-return');await p.locator('#modal[open]').waitFor();assert((await p.evaluate(()=>AllinPayDemo.getKTC())).passed);await p.locator('#modal [data-action="ktc-next"]').click();await phoneContext.close();await form(p,target,'ktc');
  for(const width of [1600,1024,768,390,320]){await p.setViewportSize({width,height:900});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),target+' KTC overflow '+width);}
  await p.setViewportSize({width:1440,height:1000});await form(p,target,2);const before=await p.locator('[data-field="directors[0].name"]').inputValue();await p.locator('[data-azure-language]').first().selectOption('zh-Hans');assert.equal(await p.locator('html').getAttribute('lang'),'zh-Hans');assert.equal(await p.locator('[data-field="directors[0].name"]').inputValue(),before);await p.locator('[data-azure-language]').first().selectOption('en');assert.equal(await p.locator('html').getAttribute('lang'),'en');assert.match(await p.locator('.step').nth(1).innerText(),/KTC verification/);await p.locator('[data-azure-language]').first().selectOption('zh-Hant');assert.match(await p.locator('.step').nth(1).innerText(),/KTC 認證/);
  checks.push(target+': OTP errors and success, seven-step navigation, preserved sidebar/brand alignment, full mobile consent/photo/review/face/error/retry/callback, expired QR, identity-change invalidation, real synthetic ID extraction + confirmation enables face-only, responsive layouts and locale switching without data mutation');
  await context.close();
 }
 // Backend registration, backup confirmation/download and one-time recovery.
 const p=await browser.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/backoffice.html#/register');await p.locator('#reg-name').fill('Azure QA');await p.locator('#login-email').fill('registration@example.com');await p.locator('#reg-password').fill('Demo1234!');await p.locator('#reg-confirm').fill('Demo1234!');await p.locator('#reg-terms').check();await click(p,'bo-register');await p.locator('#azure-code').fill('123456');await click(p,'azure-auth-check');await p.getByRole('heading',{name:'綁定驗證器',exact:true}).waitFor();await p.locator('#azure-code').fill('123456');await click(p,'azure-auth-check');await click(p,'azure-auth-finish');assert.match(await p.locator('#azure-auth-error').innerText(),/先保存/);const download=p.waitForEvent('download');await click(p,'azure-backup-download');assert.equal((await download).suggestedFilename(),'Azure-Demo-backup-codes.txt');await p.locator('#azure-backup-saved').check();await click(p,'azure-auth-finish');await p.waitForSelector('.metrics');
 for(let i=0;i<2;i++){await click(p,'logout');await click(p,'bo-logout');await p.locator('#login-email').fill('registration@example.com');await p.locator('#login-password').fill('Demo1234!');await click(p,'bo-login');await click(p,'azure-auth-recovery');await p.getByRole('heading',{name:'使用備用碼',exact:true}).waitFor();await p.locator('#azure-code').fill('DEMO-4821');await click(p,'azure-auth-check');if(!i)await p.waitForSelector('.metrics');else assert.match(await p.locator('#azure-auth-error').innerText(),/已使用/);}
 await p.close();checks.push('Registration email → authenticator setup → backup-code download/confirmation → dashboard; recovery code cannot be reused');
 const ep=await browser.newPage();ep.on('pageerror',e=>errors.push(e.message));await ep.goto(base+'/external.html#/register');for(const [id,v] of [['registerCompany','DEMO COMPANY LIMITED'],['registerLast','Demo'],['registerFirst','User'],['authEmail','new-external@example.com']])await ep.locator('#'+id).fill(v);await ep.locator('#authority').check();await ep.locator('#terms').check();await click(ep,'register');await emailOTP(ep);await ep.getByRole('heading',{name:'綁定驗證器',exact:true}).waitFor();await ep.locator('#azure-code').fill('123456');await click(ep,'azure-auth-check');await ep.locator('#azure-backup-saved').check();await click(ep,'azure-auth-finish');await ep.waitForSelector('.v2-form');await form(ep,'external',2);assert.equal(await ep.locator('[data-field="merchantEnglishName"]').inputValue(),'DEMO COMPANY LIMITED');await ep.close();checks.push('External registration and authenticator setup preserve company/contact seed');
 const expired=await browser.newPage();await expired.goto(base+'/backoffice.html#/login');await click(expired,'pick-role');await click(expired,'bo-login');await expired.locator('#azure-code').waitFor();await expired.clock.setFixedTime(new Date(Date.now()+601000));await expired.locator('#azure-code').fill('123456');await click(expired,'azure-auth-check');assert.match(await expired.locator('#azure-auth-error').innerText(),/過期/);assert.equal(await expired.locator('.metrics').count(),0);await expired.close();checks.push('OTP expiry blocks login; separate-device-context face-only flow and manual demo return code complete successfully');
 assert.deepEqual(errors,[]);fs.writeFileSync('qa-azure-report.json',JSON.stringify({passed:true,date:new Date().toISOString(),base,browser:process.env.CHROME_PATH||'Chromium',checks,errors},null,2));console.log('PASS Azure release:',checks.join('\n'));
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exit(1);});
